pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('startup-analytics') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        python -m pip install --upgrade pip
                        pip install -r requirements.txt
                        pip install pytest
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('startup-analytics') {
                    sh '''
                        . venv/bin/activate
                        pytest
                    '''
                }
            }
        }
    }
}
