pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir('startup-analytics') {
                    sh '''
                        rm -rf venv
                        python3 -m venv venv
                        . venv/bin/activate
                        python -m pip install --upgrade pip
                        pip install -r requirements.txt
                        pip install pytest httpx
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('startup-analytics') {
                    sh '''
                        . venv/bin/activate
                        pytest
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('startup-analytics') {
                    sh 'docker build -t startup-analytics .'
                }
            }
        }
    }
}
